function field = load_fields_from_netcdf(fileList, desired_field)
field = [];
  for n=1:size(fileList,1)
      field_mini = ncread(fileList(n,:), desired_field);
     if strcmp(desired_field, 'U') || ...
         strcmp(desired_field, 'V') || ...
         strcmp(desired_field, 'W') || ...
         strcmp(desired_field, 'P_HYD') || ... 
         strcmp(desired_field, 'P') || ...
         strcmp(desired_field, 'PB') || ...
         strcmp(desired_field, 'PH') || ...
         strcmp(desired_field, 'PHB') || ...
         strcmp(desired_field, 'T') || ...
	 strcmp(desired_field, 'DN')
            field = cat(4, field, field_mini);
     elseif strcmp(desired_field, 'ZNU') || ...
             strcmp(desired_field, 'ZNW') || ...
             strcmp(desired_field, 'P_TOP')
            field = cat(2, field, field_mini);
     elseif strcmp(desired_field, 'MU') || strcmp(desired_field, 'MUB')
            field = cat(3, field, field_mini);
     else
         disp('The field you are trying to load is not added to my thingy yet.')
         disp('Please check the data dimensions with $ncdump -c var_name file_name and add the')
         disp('correct concatination dimension (the dimension which contains time)')
         disp(' ')
     end
     clear functions
  end
end
